steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
        "${_SERVICE_FOLDER}",
      ]
    dir: '$HOME/neo4j-gcp-viz'

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "pull image"
    name: "gcr.io/cloud-builders/docker"
    args: ["pull", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

options:
  logStreamingOption: STREAM_ON

substitutions:
  _SERVICE_FOLDER: node
  _SERVICE_NAME: neo4j-gcp-viz

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest"